<h3><strong>11주차 한양대 기술경영 석사 김상연 2022130922</strong></h3>

<h5>NumPy 임포트</h5>

In [2]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

<h5>예제 코드 읽기</h5>

In [ ]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

<h5>배열이란 무엇입니까? </h5>

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
print(a[0])

[1 2 3 4]


<h5>기본 배열을 만드는 방법 </h5>

In [ ]:
import numpy as np
a = np.array([1, 2, 3])

In [ ]:
np.zeros(2)

array([0., 0.])

In [ ]:
np.ones(2)

array([1., 1.])

In [ ]:
np.empty(2) 

array([1., 1.])

In [ ]:
np.arange(4)

array([0, 1, 2, 3])

In [ ]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [ ]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

<h5>요소 추가, 제거 및 정렬</h5>

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [ ]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [ ]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

<h5>배열의 모양과 크기를 어떻게 알 수 있습니까? </h5>

In [ ]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim

3

In [ ]:
array_example.size

24

In [ ]:
array_example.shape

(3, 2, 4)

<h5>배열을 재구성할 수 있습니까?</h5>

In [ ]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [ ]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

<h5>1D 배열을 2D 배열로 변환하는 방법(배열에 새 축을 추가하는 방법)</h5>

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [ ]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [ ]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [ ]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [ ]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [ ]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

<h5>인덱싱 및 슬라이싱 </h5>

In [ ]:
data = np.array([1, 2, 3])

data[1]

2

In [ ]:
data[0:2]

array([1, 2])

In [ ]:
data[1:]

array([2, 3])

In [ ]:
data[-2:]

array([2, 3])

In [ ]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

[1 2 3 4]


In [ ]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [ ]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [ ]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [ ]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [ ]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [ ]:
print(a[b])

[1 2 3 4]


In [ ]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


<h5>기존 데이터에서 배열을 만드는 방법</h5>

In [ ]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [ ]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [ ]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [ ]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [ ]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b2 = a.copy()
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

<h5>기본 배열 작업 </h5>

In [ ]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [ ]:
data - ones

array([0, 1])

In [ ]:
data * data

array([1, 4])

In [ ]:
data / data

array([1., 1.])

In [ ]:
a = np.array([1, 2, 3, 4])

a.sum()

10

In [ ]:
b = np.array([[1, 1], [2, 2]])

In [ ]:
b.sum(axis=0)

array([3, 3])

In [ ]:
b.sum(axis=1)

array([2, 4])

<h5>브로드캐스팅</h5>

In [ ]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

<h5>더 유용한 배열 작업</h5>

In [ ]:
data.max()

2.0

In [ ]:
data.min()

1.0

In [ ]:
data.sum()

3.0

In [ ]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

a.sum()

4.8595784

In [ ]:
a.min()

0.05093587

In [ ]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

<h5>행렬 만들기</h5>

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
data[0, 1]

2

In [ ]:
data[1:3]


array([[3, 4],
       [5, 6]])

In [ ]:
data[0:2, 0]

array([1, 3])

In [ ]:
data.max()

6

In [ ]:
data.min()

1

In [ ]:
data.sum()

21

In [ ]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [ ]:
data.max(axis=0)

array([5, 6])

In [ ]:
data.max(axis=1)

array([2, 5, 6])

In [ ]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
rng = np.random.default_rng()  
rng.random(3) 

array([0.25562318, 0.40573624, 0.60281847])

In [ ]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
rng.random((3, 2)) 

array([[0.07492948, 0.46031402],
       [0.26651312, 0.2725364 ],
       [0.10824331, 0.62349756]])

<h5>난수 생성</h5>

In [ ]:
rng.integers(5, size=(2, 4)) 

array([[0, 4, 0, 1],
       [4, 0, 4, 3]], dtype=int64)

<h5>고유 아이템 및 카운트를 얻는 방법</h5>

In [ ]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [ ]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [ ]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [ ]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(indices)

[0 1 2]


In [ ]:
print(occurrence_count)

[2 1 1]


<h5>행렬 전치 및 변형</h5>

In [ ]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
arr = np.arange(6).reshape((2, 3))

arr

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
reversed_arr = np.flip(arr)
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [ ]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [ ]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [ ]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [ ]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [ ]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


<h5>다차원 배열 재구성 및 평면화</h5>

In [ ]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a1 = x.flatten()
a1[0] = 99
print(x) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
a2 = x.ravel()
a2[0] = 98
print(x)  

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]
